name: Download Docker Image
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image name (e.g. etenal/syzscope:ready2go)'
        required: true
        default: 'etenal/syzscope:ready2go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🧹 Maximize build space (Free up 30GB)
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 40000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: ⬇️ Pull image
        run: docker pull ${{ github.event.inputs.image }}

      - name: 📦 Save image to tar
        run: docker save -o image.tar ${{ github.event.inputs.image }}

      - name: ✂️ Split tar file (2GB per chunk)
        run: split -b 2000M image.tar image.tar.part.

      - name: ⬆️ Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-parts
          path: image.tar.part.*
          retention-days: 1
